In [ ]:
#Numpy 12 september 2026

In [ ]:
print("Hello world")

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4 , 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
# pip install numpy (to use in vsc)

In [ ]:
ls = [ [1, 2, 3], [4, 5 ,6], [7, 8, 9]   ]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(ls)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.arange(1, 35, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [ ]:
arr[1:8]

array([ 3,  5,  7,  9, 11, 13, 15])

In [ ]:
arr[:5]

array([1, 3, 5, 7, 9])

In [ ]:
arr[3:5]

array([7, 9])

In [ ]:
np.zeros((8,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(0,1,1000)

array([0.        , 0.001001  , 0.002002  , 0.003003  , 0.004004  ,
       0.00500501, 0.00600601, 0.00700701, 0.00800801, 0.00900901,
       0.01001001, 0.01101101, 0.01201201, 0.01301301, 0.01401401,
       0.01501502, 0.01601602, 0.01701702, 0.01801802, 0.01901902,
       0.02002002, 0.02102102, 0.02202202, 0.02302302, 0.02402402,
       0.02502503, 0.02602603, 0.02702703, 0.02802803, 0.02902903,
       0.03003003, 0.03103103, 0.03203203, 0.03303303, 0.03403403,
       0.03503504, 0.03603604, 0.03703704, 0.03803804, 0.03903904,
       0.04004004, 0.04104104, 0.04204204, 0.04304304, 0.04404404,
       0.04504505, 0.04604605, 0.04704705, 0.04804805, 0.04904905,
       0.05005005, 0.05105105, 0.05205205, 0.05305305, 0.05405405,
       0.05505506, 0.05605606, 0.05705706, 0.05805806, 0.05905906,
       0.06006006, 0.06106106, 0.06206206, 0.06306306, 0.06406406,
       0.06506507, 0.06606607, 0.06706707, 0.06806807, 0.06906907,
       0.07007007, 0.07107107, 0.07207207, 0.07307307, 0.07407

In [ ]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
np.random.rand(10)

array([0.08848178, 0.81006286, 0.28683228, 0.660851  , 0.61053836,
       0.15151467, 0.72544321, 0.55338419, 0.43052881, 0.28165887])

In [ ]:
np.random.randn(10, 100, 1)

array([[[ 0.92354626],
        [-1.43744575],
        [-1.8194667 ],
        [ 0.9772786 ],
        [-0.12633883],
        [-0.20774097],
        [-2.03155504],
        [ 0.55717508],
        [ 0.1845566 ],
        [-0.51644391],
        [ 1.05748894],
        [-0.67778049],
        [ 2.12861983],
        [ 0.7299811 ],
        [ 0.4869707 ],
        [ 3.29557668],
        [-0.41471722],
        [-0.78162015],
        [ 0.98019512],
        [-0.55726457],
        [-0.95087227],
        [ 0.5491021 ],
        [ 0.0386679 ],
        [ 2.14209706],
        [-0.39963033],
        [-0.63680386],
        [ 3.07032911],
        [ 1.14515807],
        [-1.02221712],
        [-0.58035925],
        [-0.57545193],
        [-1.73773673],
        [-0.76758306],
        [-1.11001972],
        [-1.28416556],
        [ 0.47952075],
        [-1.58322673],
        [-1.44361357],
        [-1.15194344],
        [ 0.74989584],
        [-0.84438432],
        [ 0.05820741],
        [-1.07077102],
        [-1

In [ ]:
np.random.rand(1, 10, 2)

array([[[0.64717485, 0.10186199],
        [0.47683853, 0.46367574],
        [0.10319679, 0.85678006],
        [0.07004077, 0.10650752],
        [0.27252465, 0.35904371],
        [0.59135094, 0.8341053 ],
        [0.69215537, 0.02370835],
        [0.35588464, 0.74268813],
        [0.73473074, 0.48760401],
        [0.01958977, 0.0334527 ]]])

In [ ]:
np.random.randn(10, 100, 10)

array([[[-0.08792369, -0.65600364,  0.38634866, ...,  1.17604974,
         -0.77664307, -0.39074169],
        [-0.27044629, -1.11469671,  0.23628664, ..., -1.02983564,
          0.84605031, -1.64294058],
        [ 0.80630704,  0.66208346,  2.21793081, ..., -0.03822332,
         -1.84961956,  0.06185095],
        ...,
        [-1.61902945,  0.94673585,  0.7539115 , ...,  0.47774303,
          0.95708008,  0.88704815],
        [ 0.24347071, -0.63610929, -0.33649372, ...,  0.26453553,
         -1.56547671, -0.92361221],
        [ 1.40084341, -1.12106695, -0.5177494 , ..., -0.62200851,
         -0.76575912, -0.3543421 ]],

       [[ 1.47305957,  0.27434214, -0.3478251 , ..., -0.13121504,
         -1.26902707, -0.09776889],
        [ 0.75553044, -0.15108402,  2.36155825, ..., -0.50791835,
          0.05651805,  0.57058857],
        [ 0.48905723, -1.21448375,  0.53397152, ..., -0.56452602,
          1.5496352 ,  1.76977548],
        ...,
        [ 1.44388986,  0.69990904,  1.3835974 , ..., -

In [ ]:
arr = np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
arr[3::2]

array([14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr[3::3]

array([14, 17, 20, 23, 26, 29])

In [ ]:
arr = np.arange(1,31).reshape(6,5)
# 6 x 5 = 30 .

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr = np.arange(1,31).reshape(5,6)
arr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
a1 = [1,2,3,4,5]
a2 = [6,7,8,9,10]

a1 + a2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
ls = [1,2,3,4,5]
arr = np.array(ls)

In [ ]:
arr + 10

array([11, 12, 13, 14, 15])

In [ ]:
arr2 = np.arange(1, 10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
a = [4, 5, 6, 7, 8, 9]

In [ ]:
a[0] = 2
b = a.copy()

In [ ]:
b

[2, 5, 6, 7, 8, 9]